### ISSUE TITLE
Special characters in the database

### ISSUE THREAD

**Issue by yeshancqcq** [EarthCubeGeochron/Sparrow#141]
After importing the datasheet, some special characters are not recognized correctly.

For example:

![image](https://user-images.githubusercontent.com/11675281/117554957-9d557e80-b020-11eb-9cbd-f589d1e5b977.png)

**Comment by yeshancqcq** [comment]
> @yeshancqcq , Which special character is it not recognizing? I assume you mean the `√˚` is replacing whatever the right character is supposed to be.

In the screenshot it is ü.  There are several others in the database, such as ä, ý,  etc.

**Comment by davenquinn** [comment]
Are you clear that the data is garbled _in the database_ or is it it a frontend issue?

This is probably an importer (string encoding) problem, since strings on the database side are stored as UTF-8. You can check this by manually overriding one of the strings with the correct value in Postico, and seeing if it propagates into Sparrow's frontend.

**Comment by davenquinn** [comment]
ah I see your screenshot is from Postico. So it's in the database wrong. Still seems like an importer issue.

**Comment by davenquinn** [comment]
I think we solved this, right @yeshancqcq ?
