### ISSUE TITLE
Intermittent failure distinguishing `unit` and `error_unit` relationships on automapping

### ISSUE THREAD

**Issue by davenquinn** [EarthCubeGeochron/Sparrow#66]
There seems to be some sort of occasional failure in automapping, which manifests with the `DatumType._error_unit` relationship not being properly distinguished from `DatumType._unit`. On import, we end up unpredictably partitioning data into sets with and without error units.

In the testing suite, this manifests as occasional (maybe 1 in 5 runs) failures in the `test_import_interface` series of tests. When the condition is encountered, four tests in that file fail. We've created a few that do a reasonable job of isolating the problem, but we haven't created a test without the intermittency. Perhaps this is indicative of some sort of race condition or threading problems within Sparrow's database connection code?

This issue has likely been encountered "in the wild" by @thefallingduck when bulk-importing SIMS data.

**Comment by thefallingduck** [comment]
I may have found a related error with duplicate values for `Datum.value` when loading by `sessions`. If adjacent analyses have the same identical `Datum.value` they are dropped from one or more of the analyses. This manifested in the SIMS data import with the stage `X` and `Y` coordinates because of the gridded pattern of analyses (duplicate `X` or `Y` for adjacent analyses). Given the way I handle replacing `Null` values with a number, this likely happens with those datum, too, but is less of a concern.

Added a test on the `wisc-sims` branch off development that recreates this as viewed in postico. `test_duplicate_datum_import` in `test_importer_api.py`. It doesn't yet look for the number of unique analyses expected, however.

**Comment by Idzikowski-Casey** [comment]
It appears that the intermittent failing occurs only when API is running. When the API wasn't up I ran `sparrow test` multiple times and the tests consistently failed. However, after `sparrow up`, when the API was running, the tests continued to fail intermittently.

**Comment by davenquinn** [comment]
OK @Idzikowski-Casey, this is interesting information, it seems to suggest that there is some sort of race condition. Things _always_ fail when the API isn't running, huh. These things should be isolated but there could be some sort of transaction/locking effects...

**Comment by davenquinn** [comment]
Hm. I wasn't able to duplicate this.

**Comment by Idzikowski-Casey** [comment]
@davenquinn Spent some time this morning trying to replicate the behavior I saw. I DID get them to continuously fail (6 times in a row as of typing this response). How I did it:

- run `sparrow up`
- delete the running docker images for the `sparrow db` and the `sparrow backend`
- run `sparrow test`

The 5 tests in `test_import_interface` should fail continuously while all others pass.

**Comment by Idzikowski-Casey** [comment]
@davenquinn I just created a test that is intermittently failing when asserting `db.session.dirty` only has 1 change. This test is [here](https://github.com/EarthCubeGeochron/Sparrow/blob/tags/backend/sparrow_tests/test_tags.py#L51).

It looks like for some reason the model that I queried through the session was added to `dirty` even though I did not change it in any way.
