### ISSUE TITLE
Sparrow default database not building properly

### ISSUE THREAD

**Issue by thefallingduck** [EarthCubeGeochron/Sparrow#76]
After recent changes, @yeshancqcq and @thefallingduck encountered an issue with new database creation after `sparrow db-drop`. The db docker container is created but the SQL statements to make the default Sparrow database do not print out in the command line. Postico can connect through the usual connection, but the database created looks like the attached image. This is happening after #64 but may be related to a different merge from earlier.

Also... When using `sparrow --verbose init` this is the output that occurs...

`(base) macrostrats-mbp:Sparrow-WiscSIMS macrostrat$ sparrow --verbose init
sparrow_cli:    args: ('init',)
sparrow_cli.util:    docker-compose exec backend true
sparrow_cli.util:    docker-compose run --rm backend /app/sparrow/__main__.py init
Creating network "wiscsims_default" with the default driver
Creating wiscsims_db_1 ... done
db:None - no response
Waiting for database...
`

<img width="1058" alt="Screen Shot 2021-03-23 at 3 01 43 PM" src="https://user-images.githubusercontent.com/11468682/112212637-394f3600-8beb-11eb-9e75-16fa269c7bc4.png">

**Comment by davenquinn** [comment]
OK so the issue was created by me a few weeks ago in ebda794, where I was trying to improve and centralize [database helper](https://github.com/EarthCubeGeochron/Sparrow/blob/83fc1789af28285936b23ba4e64b2259c3654bd5/backend/sparrow/database/util.py#L125) functions as part of a broader push to bring database lifecycle management into the application.

I ended up calling `pg_isready` with a `-p None` CLI flag, which caused an error and "endless wait" loop. By happenstance, when the same function is called in the testing instance, port 5432 is provided, so we missed this error. Big one!

**Comment by davenquinn** [comment]
This will be fixed in the `v2.0.0.beta3` release.
